src/entities/asset/asset.ts
Signed-off-by: Robert Jefe Lindstaedt <robert.lindstaedt@gmail.com>
=> fix(assets): harmonize query options

src/entities/person/channel-user.ts
https://github.com/c-commerce/charles-client-api/pull/249
=> feat(channel user): verify

src/entities/url-shortener/url-shortener.ts
for ui: https://github.com/c-commerce/charles-agent-ui/pull/1000
=> feat(shortener): add person & feed params

src/entities/_base/index.ts
TECH-824
https://github.com/c-commerce/charles-client-api/pull/349
=> feat(entity base): allow clone

src/cloud/entities/interverse/api-key/api-key.ts, src/cloud/index.ts
- add key to api-key
- rename organisation to organization
=> feat: add key for api-key

src/entities/url-shortener/url-shortener.ts
**What**: 
subdomains for creating short links.
=> feat: domain

src/analytics/analytics.ts, src/universe/index.ts
=> feat(analytics): add subscription events analytics

src/charles.spec.ts, src/charles.ts
Signed-off-by: Robert Jefe Lindstaedt <robert.lindstaedt@gmail.com>
=> fix(SDK/universe): allow overriding host in factory

src/entities/person/channel-user.ts
- add delete functionality to the Channel User Entity
TECH-2089
=> feat(entity): enable delete for channel user entity

src/entities/_base/index.ts
- we are now able to pass query parameters to the delete call of the base entity
TECH-1668
=> feat(entity): add delete options for delete operation of base entity

src/entities/message-subscription/message-subscription.ts
- fix logic interfaces related to improved json logic
TECH-2107
=> refactor(message-subscription): imporve logic interfaces

src/universe/index.ts
Signed-off-by: Robert Jefe Lindstaedt <robert.lindstaedt@gmail.com>
=> feat(universe): do not require multiverse to be up

src/universe/index.ts
Details: https://hello-charles.slack.com/archives/C022X7T7EAV/p1657206181255709
=> fix(search): query string format for search with more than 20 categories

src/cloud/entities/universe/universe.ts, src/universe/index.ts
Undo change of e0e2834d36b8a67c8807ab7fc2edb32a11450beb
=> fix(universe.ts): revert breaking change to universe.ts

src/entities/person/analytics.ts
- extend analytics entity for storefront_vendor_tags
TECH-3225
=> feat(analytics): add strore-front-vendor to analytics entity

src/entities/notification-campaign/notification-campaign.ts
- extend NotificationCampaignTestRawPayload with static entry and static entries interface
=> feat(notification-campaign): add static contact interface

src/entities/message-template/message-template.ts
Message Templates: display the wapi error message on a failing submit
=> fix(MessageTemplates): display the wapi error message on a failing submit

src/entities/message-subscription/message-subscription.ts, src/entities/person/person.ts
Implements the new sugar endpoint for a streamlined message subscription instance flow.
=> feat(person): implement optin sugar handler

src/entities/data-export/data-export.ts, src/entities/data-export/data-meta.ts, src/entities/data-export/index.ts, src/universe/index.ts
Adds endpoints for a generic stored procedure execution strategy. 
Might rename in the future to reflect that in the if this is used elsewhere.
=> Feat: added endpoints for data extract

src/universe/index.ts
- support query params for customProperties
https://app.clickup.com/t/24327122/TECH-4876
=> feat(universe): add options to customProperties

.github/install-python2.sh, .github/workflows/node.yaml
https://app.clickup.com/t/86697qmzz
=> fix:added install step for python2

src/entities/storefront/storefront.ts
Adds storefront uninstall routes
=> feat(storefronts): added storefront uninstall route

src/realtime/index.ts, src/realtime/presence/__tests__/presence-entity-manager.spec.ts, src/realtime/presence/__tests__/presence-handler.spec.ts, src/realtime/presence/presence-entity-manager.ts, src/realtime/presence/presence-handler.ts, src/universe/index.ts
https://app.clickup.com/t/24327122/TECH-3847
=> feat(Presence): added support for extra payload

src/cloud/entities/universe/universe.ts
missing field (migrations) added
=> fix(cloud.universe): fix cloud universe deserialization

src/entities/product-category/product-category.ts, src/helpers/case-convert-type.ts
dependant on https://github.com/c-commerce/charles-client-api/pull/1336
=> feat(ProductCategory): added support for products_count

src/entities/message-template/message-template.ts
- add type support for submit_history property
=> feat(MessageTemplate): add submit_history type support

src/entities/message-broker/message-broker.ts
add new types to MessageBroker
=> feat(MessageBroker): add status typing

src/universe/me.ts, src/universe/universe.spec.ts
Tasks
* https://app.clickup.com/t/861mj27rj
* https://app.clickup.com/t/24327122/TECH-6226
=> feat(me): remove 7 message template favorites limit

src/entities/person/person-contact.ts, src/entities/person/person.ts, src/universe/index.ts
Adds entity to work with optimized people endpoint
https://app.clickup.com/t/24327122/TECH-6192
=> feat(person-contact): add entity

package-lock.json, src/analytics/analytics.ts, src/entities/notification-campaign/notification-campaign.ts, src/universe/index.ts
fix(Analytics): minor typing fix
=> feat(Campaign): enable scheduling

src/universe/index.ts
updated interface and passed export fn to personContact
=> feat(contact-export)

src/analytics/analytics.ts, src/universe/analytics.ts
https://app.clickup.com/t/24327122/TECH-5908
=> feat(analytics): add message broker reports

src/@types/json-patch.ts, src/entities/_base/index.ts, src/helpers/__tests__/json-patch.spec.ts, src/helpers/json-patch.ts, src/realtime/presence/presence-handler.ts, src/universe/me.ts, test/entities/base.test.ts
https://www.notion.so/hellocharles/Just-diff-JSON-serialisation-produce-faulty-results-b263be9134e34693a481749fad6cf3c8?pvs=4
=> fixed(Entity): properly handled undefined values

package-lock.json, src/entities/notification-campaign/notification-campaign.ts
https://app.clickup.com/t/24327122/TECH-8440
=> feat: deprecated legacy publish

src/eventing/feeds/event.ts, src/messaging/message.ts
https://app.clickup.com/t/24327122/TECH-8971
=> feat(message): add held field to message

src/entities/crm/crm.ts
https://app.clickup.com/t/24327122/TECH-9448
=> feat(klaviyo-detail-sync): added handling for single list sync

src/entities/configuration/configuration.ts
https://app.clickup.com/t/24327122/TECH-9455
=> feat(attrib window settings): added typing for configuration.settings

src/entities/import/import.ts
https://hello-charles-team.atlassian.net/browse/PLAT-294
=> feat(Import): added metadata

src/universe/index.ts
Allows passing endpoint version to setup endpoint
=> feat(KlaviyoOath): Allow passing version to setup endpoint

src/universe/index.ts
Ticket:
- https://hello-charles-team.atlassian.net/browse/OCT-12261
Added the missing types
=> feat: add update configs type
